<?php
/**
 * AnalysisSettings
 *
 * PHP version 5
 *
 * @category Class
 * @package  ProWritingAidSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ProWritingAidSDK\Model;

use \ArrayAccess;
use \ProWritingAidSDK\ObjectSerializer;

/**
 * AnalysisSettings Class Doc Comment
 *
 * @category Class
 * @package  ProWritingAidSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AnalysisSettings implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AnalysisSettings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'shortest_average_sentence_length' => 'int',
        'longest_average_sentence_length' => 'int',
        'longest_individual_sentence' => 'int',
        'highest_passive_index' => 'int',
        'max_glue_index' => 'int',
        'min_sentence_variety' => 'int',
        'highest_pronoun_percentage' => 'double',
        'lowest_pronoun_percentage' => 'double',
        'highest_academic_pronoun_percentage' => 'double',
        'highest_initial_pronoun_percentage' => 'double',
        'lowest_initial_pronoun_percentage' => 'double',
        'lowest_we_we_score' => 'double',
        'longest_average_paragraph_length' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'shortest_average_sentence_length' => 'int32',
        'longest_average_sentence_length' => 'int32',
        'longest_individual_sentence' => 'int32',
        'highest_passive_index' => 'int32',
        'max_glue_index' => 'int32',
        'min_sentence_variety' => 'int32',
        'highest_pronoun_percentage' => 'double',
        'lowest_pronoun_percentage' => 'double',
        'highest_academic_pronoun_percentage' => 'double',
        'highest_initial_pronoun_percentage' => 'double',
        'lowest_initial_pronoun_percentage' => 'double',
        'lowest_we_we_score' => 'double',
        'longest_average_paragraph_length' => 'double'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shortest_average_sentence_length' => 'ShortestAverageSentenceLength',
        'longest_average_sentence_length' => 'LongestAverageSentenceLength',
        'longest_individual_sentence' => 'LongestIndividualSentence',
        'highest_passive_index' => 'HighestPassiveIndex',
        'max_glue_index' => 'MaxGlueIndex',
        'min_sentence_variety' => 'MinSentenceVariety',
        'highest_pronoun_percentage' => 'HighestPronounPercentage',
        'lowest_pronoun_percentage' => 'LowestPronounPercentage',
        'highest_academic_pronoun_percentage' => 'HighestAcademicPronounPercentage',
        'highest_initial_pronoun_percentage' => 'HighestInitialPronounPercentage',
        'lowest_initial_pronoun_percentage' => 'LowestInitialPronounPercentage',
        'lowest_we_we_score' => 'LowestWeWeScore',
        'longest_average_paragraph_length' => 'LongestAverageParagraphLength'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shortest_average_sentence_length' => 'setShortestAverageSentenceLength',
        'longest_average_sentence_length' => 'setLongestAverageSentenceLength',
        'longest_individual_sentence' => 'setLongestIndividualSentence',
        'highest_passive_index' => 'setHighestPassiveIndex',
        'max_glue_index' => 'setMaxGlueIndex',
        'min_sentence_variety' => 'setMinSentenceVariety',
        'highest_pronoun_percentage' => 'setHighestPronounPercentage',
        'lowest_pronoun_percentage' => 'setLowestPronounPercentage',
        'highest_academic_pronoun_percentage' => 'setHighestAcademicPronounPercentage',
        'highest_initial_pronoun_percentage' => 'setHighestInitialPronounPercentage',
        'lowest_initial_pronoun_percentage' => 'setLowestInitialPronounPercentage',
        'lowest_we_we_score' => 'setLowestWeWeScore',
        'longest_average_paragraph_length' => 'setLongestAverageParagraphLength'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shortest_average_sentence_length' => 'getShortestAverageSentenceLength',
        'longest_average_sentence_length' => 'getLongestAverageSentenceLength',
        'longest_individual_sentence' => 'getLongestIndividualSentence',
        'highest_passive_index' => 'getHighestPassiveIndex',
        'max_glue_index' => 'getMaxGlueIndex',
        'min_sentence_variety' => 'getMinSentenceVariety',
        'highest_pronoun_percentage' => 'getHighestPronounPercentage',
        'lowest_pronoun_percentage' => 'getLowestPronounPercentage',
        'highest_academic_pronoun_percentage' => 'getHighestAcademicPronounPercentage',
        'highest_initial_pronoun_percentage' => 'getHighestInitialPronounPercentage',
        'lowest_initial_pronoun_percentage' => 'getLowestInitialPronounPercentage',
        'lowest_we_we_score' => 'getLowestWeWeScore',
        'longest_average_paragraph_length' => 'getLongestAverageParagraphLength'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shortest_average_sentence_length'] = isset($data['shortest_average_sentence_length']) ? $data['shortest_average_sentence_length'] : 11;
        $this->container['longest_average_sentence_length'] = isset($data['longest_average_sentence_length']) ? $data['longest_average_sentence_length'] : 18;
        $this->container['longest_individual_sentence'] = isset($data['longest_individual_sentence']) ? $data['longest_individual_sentence'] : 30;
        $this->container['highest_passive_index'] = isset($data['highest_passive_index']) ? $data['highest_passive_index'] : 25;
        $this->container['max_glue_index'] = isset($data['max_glue_index']) ? $data['max_glue_index'] : 40;
        $this->container['min_sentence_variety'] = isset($data['min_sentence_variety']) ? $data['min_sentence_variety'] : 3;
        $this->container['highest_pronoun_percentage'] = isset($data['highest_pronoun_percentage']) ? $data['highest_pronoun_percentage'] : 15.0;
        $this->container['lowest_pronoun_percentage'] = isset($data['lowest_pronoun_percentage']) ? $data['lowest_pronoun_percentage'] : 4.0;
        $this->container['highest_academic_pronoun_percentage'] = isset($data['highest_academic_pronoun_percentage']) ? $data['highest_academic_pronoun_percentage'] : 2.0;
        $this->container['highest_initial_pronoun_percentage'] = isset($data['highest_initial_pronoun_percentage']) ? $data['highest_initial_pronoun_percentage'] : 30.0;
        $this->container['lowest_initial_pronoun_percentage'] = isset($data['lowest_initial_pronoun_percentage']) ? $data['lowest_initial_pronoun_percentage'] : 0.0;
        $this->container['lowest_we_we_score'] = isset($data['lowest_we_we_score']) ? $data['lowest_we_we_score'] : 0.6;
        $this->container['longest_average_paragraph_length'] = isset($data['longest_average_paragraph_length']) ? $data['longest_average_paragraph_length'] : 6.0;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['shortest_average_sentence_length'] === null) {
            $invalidProperties[] = "'shortest_average_sentence_length' can't be null";
        }
        if ($this->container['longest_average_sentence_length'] === null) {
            $invalidProperties[] = "'longest_average_sentence_length' can't be null";
        }
        if ($this->container['longest_individual_sentence'] === null) {
            $invalidProperties[] = "'longest_individual_sentence' can't be null";
        }
        if ($this->container['highest_passive_index'] === null) {
            $invalidProperties[] = "'highest_passive_index' can't be null";
        }
        if ($this->container['max_glue_index'] === null) {
            $invalidProperties[] = "'max_glue_index' can't be null";
        }
        if ($this->container['min_sentence_variety'] === null) {
            $invalidProperties[] = "'min_sentence_variety' can't be null";
        }
        if ($this->container['highest_pronoun_percentage'] === null) {
            $invalidProperties[] = "'highest_pronoun_percentage' can't be null";
        }
        if ($this->container['lowest_pronoun_percentage'] === null) {
            $invalidProperties[] = "'lowest_pronoun_percentage' can't be null";
        }
        if ($this->container['highest_academic_pronoun_percentage'] === null) {
            $invalidProperties[] = "'highest_academic_pronoun_percentage' can't be null";
        }
        if ($this->container['highest_initial_pronoun_percentage'] === null) {
            $invalidProperties[] = "'highest_initial_pronoun_percentage' can't be null";
        }
        if ($this->container['lowest_initial_pronoun_percentage'] === null) {
            $invalidProperties[] = "'lowest_initial_pronoun_percentage' can't be null";
        }
        if ($this->container['lowest_we_we_score'] === null) {
            $invalidProperties[] = "'lowest_we_we_score' can't be null";
        }
        if ($this->container['longest_average_paragraph_length'] === null) {
            $invalidProperties[] = "'longest_average_paragraph_length' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shortest_average_sentence_length
     *
     * @return int
     */
    public function getShortestAverageSentenceLength()
    {
        return $this->container['shortest_average_sentence_length'];
    }

    /**
     * Sets shortest_average_sentence_length
     *
     * @param int $shortest_average_sentence_length shortest_average_sentence_length
     *
     * @return $this
     */
    public function setShortestAverageSentenceLength($shortest_average_sentence_length)
    {
        $this->container['shortest_average_sentence_length'] = $shortest_average_sentence_length;

        return $this;
    }

    /**
     * Gets longest_average_sentence_length
     *
     * @return int
     */
    public function getLongestAverageSentenceLength()
    {
        return $this->container['longest_average_sentence_length'];
    }

    /**
     * Sets longest_average_sentence_length
     *
     * @param int $longest_average_sentence_length longest_average_sentence_length
     *
     * @return $this
     */
    public function setLongestAverageSentenceLength($longest_average_sentence_length)
    {
        $this->container['longest_average_sentence_length'] = $longest_average_sentence_length;

        return $this;
    }

    /**
     * Gets longest_individual_sentence
     *
     * @return int
     */
    public function getLongestIndividualSentence()
    {
        return $this->container['longest_individual_sentence'];
    }

    /**
     * Sets longest_individual_sentence
     *
     * @param int $longest_individual_sentence longest_individual_sentence
     *
     * @return $this
     */
    public function setLongestIndividualSentence($longest_individual_sentence)
    {
        $this->container['longest_individual_sentence'] = $longest_individual_sentence;

        return $this;
    }

    /**
     * Gets highest_passive_index
     *
     * @return int
     */
    public function getHighestPassiveIndex()
    {
        return $this->container['highest_passive_index'];
    }

    /**
     * Sets highest_passive_index
     *
     * @param int $highest_passive_index highest_passive_index
     *
     * @return $this
     */
    public function setHighestPassiveIndex($highest_passive_index)
    {
        $this->container['highest_passive_index'] = $highest_passive_index;

        return $this;
    }

    /**
     * Gets max_glue_index
     *
     * @return int
     */
    public function getMaxGlueIndex()
    {
        return $this->container['max_glue_index'];
    }

    /**
     * Sets max_glue_index
     *
     * @param int $max_glue_index max_glue_index
     *
     * @return $this
     */
    public function setMaxGlueIndex($max_glue_index)
    {
        $this->container['max_glue_index'] = $max_glue_index;

        return $this;
    }

    /**
     * Gets min_sentence_variety
     *
     * @return int
     */
    public function getMinSentenceVariety()
    {
        return $this->container['min_sentence_variety'];
    }

    /**
     * Sets min_sentence_variety
     *
     * @param int $min_sentence_variety min_sentence_variety
     *
     * @return $this
     */
    public function setMinSentenceVariety($min_sentence_variety)
    {
        $this->container['min_sentence_variety'] = $min_sentence_variety;

        return $this;
    }

    /**
     * Gets highest_pronoun_percentage
     *
     * @return double
     */
    public function getHighestPronounPercentage()
    {
        return $this->container['highest_pronoun_percentage'];
    }

    /**
     * Sets highest_pronoun_percentage
     *
     * @param double $highest_pronoun_percentage highest_pronoun_percentage
     *
     * @return $this
     */
    public function setHighestPronounPercentage($highest_pronoun_percentage)
    {
        $this->container['highest_pronoun_percentage'] = $highest_pronoun_percentage;

        return $this;
    }

    /**
     * Gets lowest_pronoun_percentage
     *
     * @return double
     */
    public function getLowestPronounPercentage()
    {
        return $this->container['lowest_pronoun_percentage'];
    }

    /**
     * Sets lowest_pronoun_percentage
     *
     * @param double $lowest_pronoun_percentage lowest_pronoun_percentage
     *
     * @return $this
     */
    public function setLowestPronounPercentage($lowest_pronoun_percentage)
    {
        $this->container['lowest_pronoun_percentage'] = $lowest_pronoun_percentage;

        return $this;
    }

    /**
     * Gets highest_academic_pronoun_percentage
     *
     * @return double
     */
    public function getHighestAcademicPronounPercentage()
    {
        return $this->container['highest_academic_pronoun_percentage'];
    }

    /**
     * Sets highest_academic_pronoun_percentage
     *
     * @param double $highest_academic_pronoun_percentage highest_academic_pronoun_percentage
     *
     * @return $this
     */
    public function setHighestAcademicPronounPercentage($highest_academic_pronoun_percentage)
    {
        $this->container['highest_academic_pronoun_percentage'] = $highest_academic_pronoun_percentage;

        return $this;
    }

    /**
     * Gets highest_initial_pronoun_percentage
     *
     * @return double
     */
    public function getHighestInitialPronounPercentage()
    {
        return $this->container['highest_initial_pronoun_percentage'];
    }

    /**
     * Sets highest_initial_pronoun_percentage
     *
     * @param double $highest_initial_pronoun_percentage highest_initial_pronoun_percentage
     *
     * @return $this
     */
    public function setHighestInitialPronounPercentage($highest_initial_pronoun_percentage)
    {
        $this->container['highest_initial_pronoun_percentage'] = $highest_initial_pronoun_percentage;

        return $this;
    }

    /**
     * Gets lowest_initial_pronoun_percentage
     *
     * @return double
     */
    public function getLowestInitialPronounPercentage()
    {
        return $this->container['lowest_initial_pronoun_percentage'];
    }

    /**
     * Sets lowest_initial_pronoun_percentage
     *
     * @param double $lowest_initial_pronoun_percentage lowest_initial_pronoun_percentage
     *
     * @return $this
     */
    public function setLowestInitialPronounPercentage($lowest_initial_pronoun_percentage)
    {
        $this->container['lowest_initial_pronoun_percentage'] = $lowest_initial_pronoun_percentage;

        return $this;
    }

    /**
     * Gets lowest_we_we_score
     *
     * @return double
     */
    public function getLowestWeWeScore()
    {
        return $this->container['lowest_we_we_score'];
    }

    /**
     * Sets lowest_we_we_score
     *
     * @param double $lowest_we_we_score lowest_we_we_score
     *
     * @return $this
     */
    public function setLowestWeWeScore($lowest_we_we_score)
    {
        $this->container['lowest_we_we_score'] = $lowest_we_we_score;

        return $this;
    }

    /**
     * Gets longest_average_paragraph_length
     *
     * @return double
     */
    public function getLongestAverageParagraphLength()
    {
        return $this->container['longest_average_paragraph_length'];
    }

    /**
     * Sets longest_average_paragraph_length
     *
     * @param double $longest_average_paragraph_length longest_average_paragraph_length
     *
     * @return $this
     */
    public function setLongestAverageParagraphLength($longest_average_paragraph_length)
    {
        $this->container['longest_average_paragraph_length'] = $longest_average_paragraph_length;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


