<?php
/**
 * AnalysisSummarySubItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ProWritingAidSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ProWritingAidSDK;

/**
 * AnalysisSummarySubItemTest Class Doc Comment
 *
 * @category    Class
 * @description AnalysisSummarySubItem
 * @package     ProWritingAidSDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AnalysisSummarySubItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AnalysisSummarySubItem"
     */
    public function testAnalysisSummarySubItem()
    {
    }

    /**
     * Test attribute "tag_ids"
     */
    public function testPropertyTagIds()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "suggestion_category"
     */
    public function testPropertySuggestionCategory()
    {
    }

    /**
     * Test attribute "sub_category"
     */
    public function testPropertySubCategory()
    {
    }

    /**
     * Test attribute "search_term"
     */
    public function testPropertySearchTerm()
    {
    }
}
