<?php
/**
 * AnalysisSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AnalysisSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description Represents report summary
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AnalysisSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AnalysisSummary"
     */
    public function testAnalysisSummary()
    {
    }

    /**
     * Test attribute "report_display_name"
     */
    public function testPropertyReportDisplayName()
    {
    }

    /**
     * Test attribute "report_name"
     */
    public function testPropertyReportName()
    {
    }

    /**
     * Test attribute "summary_items"
     */
    public function testPropertySummaryItems()
    {
    }

    /**
     * Test attribute "number_of_issues"
     */
    public function testPropertyNumberOfIssues()
    {
    }

    /**
     * Test attribute "report_description"
     */
    public function testPropertyReportDescription()
    {
    }
}
