<?php
/**
 * AnalysisSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AnalysisSettingsTest Class Doc Comment
 *
 * @category    Class */
// * @description AnalysisSettings
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AnalysisSettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AnalysisSettings"
     */
    public function testAnalysisSettings()
    {
    }

    /**
     * Test attribute "shortest_average_sentence_length"
     */
    public function testPropertyShortestAverageSentenceLength()
    {
    }

    /**
     * Test attribute "longest_average_sentence_length"
     */
    public function testPropertyLongestAverageSentenceLength()
    {
    }

    /**
     * Test attribute "longest_individual_sentence"
     */
    public function testPropertyLongestIndividualSentence()
    {
    }

    /**
     * Test attribute "highest_passive_index"
     */
    public function testPropertyHighestPassiveIndex()
    {
    }

    /**
     * Test attribute "max_glue_index"
     */
    public function testPropertyMaxGlueIndex()
    {
    }

    /**
     * Test attribute "min_sentence_variety"
     */
    public function testPropertyMinSentenceVariety()
    {
    }

    /**
     * Test attribute "highest_pronoun_percentage"
     */
    public function testPropertyHighestPronounPercentage()
    {
    }

    /**
     * Test attribute "lowest_pronoun_percentage"
     */
    public function testPropertyLowestPronounPercentage()
    {
    }

    /**
     * Test attribute "highest_academic_pronoun_percentage"
     */
    public function testPropertyHighestAcademicPronounPercentage()
    {
    }

    /**
     * Test attribute "highest_initial_pronoun_percentage"
     */
    public function testPropertyHighestInitialPronounPercentage()
    {
    }

    /**
     * Test attribute "lowest_initial_pronoun_percentage"
     */
    public function testPropertyLowestInitialPronounPercentage()
    {
    }

    /**
     * Test attribute "lowest_we_we_score"
     */
    public function testPropertyLowestWeWeScore()
    {
    }

    /**
     * Test attribute "longest_average_paragraph_length"
     */
    public function testPropertyLongestAverageParagraphLength()
    {
    }
}
