<?php
/**
 * DocTagTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ProWritingAidSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ProWritingAidSDK;

/**
 * DocTagTest Class Doc Comment
 *
 * @category    Class
 * @description DocTag
 * @package     ProWritingAidSDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocTagTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DocTag"
     */
    public function testDocTag()
    {
    }

    /**
     * Test attribute "start_pos"
     */
    public function testPropertyStartPos()
    {
    }

    /**
     * Test attribute "end_pos"
     */
    public function testPropertyEndPos()
    {
    }

    /**
     * Test attribute "report"
     */
    public function testPropertyReport()
    {
    }

    /**
     * Test attribute "urls"
     */
    public function testPropertyUrls()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "category_display_name"
     */
    public function testPropertyCategoryDisplayName()
    {
    }

    /**
     * Test attribute "subcategory"
     */
    public function testPropertySubcategory()
    {
    }

    /**
     * Test attribute "hint"
     */
    public function testPropertyHint()
    {
    }

    /**
     * Test attribute "suggestions"
     */
    public function testPropertySuggestions()
    {
    }

    /**
     * Test attribute "is_sub_tag"
     */
    public function testPropertyIsSubTag()
    {
    }

    /**
     * Test attribute "help_id"
     */
    public function testPropertyHelpId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "invisible"
     */
    public function testPropertyInvisible()
    {
    }
}
