<?php
/**
 * EntryMeaningTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EntryMeaningTest Class Doc Comment
 *
 * @category    Class */
// * @description Thesaurus meaning in one context
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EntryMeaningTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EntryMeaning"
     */
    public function testEntryMeaning()
    {
    }

    /**
     * Test attribute "meaning"
     */
    public function testPropertyMeaning()
    {
    }

    /**
     * Test attribute "part_of_speech"
     */
    public function testPropertyPartOfSpeech()
    {
    }

    /**
     * Test attribute "synonims"
     */
    public function testPropertySynonims()
    {
    }
}
