<?php
/**
 * UserDocumentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserDocumentTest Class Doc Comment
 *
 * @category    Class */
// * @description UserDocument
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserDocumentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserDocument"
     */
    public function testUserDocument()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "preview"
     */
    public function testPropertyPreview()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }

    /**
     * Test attribute "document_id"
     */
    public function testPropertyDocumentId()
    {
    }

    /**
     * Test attribute "auto_save_last_modified"
     */
    public function testPropertyAutoSaveLastModified()
    {
    }

    /**
     * Test attribute "grammar_score"
     */
    public function testPropertyGrammarScore()
    {
    }

    /**
     * Test attribute "style_score"
     */
    public function testPropertyStyleScore()
    {
    }

    /**
     * Test attribute "spelling_score"
     */
    public function testPropertySpellingScore()
    {
    }

    /**
     * Test attribute "term_score"
     */
    public function testPropertyTermScore()
    {
    }

    /**
     * Test attribute "overall_score"
     */
    public function testPropertyOverallScore()
    {
    }
}
