<?php
/**
 * WordCloudRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ProWritingAidSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ProWritingAidSDK;

/**
 * WordCloudRequestTest Class Doc Comment
 *
 * @category    Class
 * @description WordCloudRequest
 * @package     ProWritingAidSDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WordCloudRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WordCloudRequest"
     */
    public function testWordCloudRequest()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "orientation"
     */
    public function testPropertyOrientation()
    {
    }

    /**
     * Test attribute "case_method"
     */
    public function testPropertyCaseMethod()
    {
    }

    /**
     * Test attribute "palette_name"
     */
    public function testPropertyPaletteName()
    {
    }

    /**
     * Test attribute "maximum_word_count"
     */
    public function testPropertyMaximumWordCount()
    {
    }

    /**
     * Test attribute "remove_common_words"
     */
    public function testPropertyRemoveCommonWords()
    {
    }

    /**
     * Test attribute "font_name"
     */
    public function testPropertyFontName()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "only_sentiment_words"
     */
    public function testPropertyOnlySentimentWords()
    {
    }

    /**
     * Test attribute "style"
     */
    public function testPropertyStyle()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }
}
